nazwa=open('zadania.txt','w')
nazwa.write('Ala ma kota')
nazwa.close()
nazwa2=open('zadania.txt').read()
print(nazwa2)
print('-------------------')
nazwa=open('zadania.txt','a')
nazwa.write('\nKot jest czarny')
nazwa.close()
nazwa2=open('zadania.txt').read()
print(nazwa2)
